name: go-proxy-bingai-release

on:
  push:
    branches: [ "harry_fork" ]
  pull_request:
    branches: [ "harry_fork" ]

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Shanghai

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}        

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: ./docker/Dockerfile  
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            docker.io/${{ github.repository }}:${{ github.ref_name }}
          cache-from: type=registry,ref=${{ github.repository }}:cache
          cache-to: type=registry,ref=${{ github.repository }}:cache,mode=max   
